### ISSUE TITLE
How to get 2D keypoints and corresponding 3D coordinates

### ISSUE THREAD

**Issue by ZHENGXi-git** [hankyang94/ConformalKeypoint#2]
Dear authors, thanks for your wonderful work!!!
I would like to know how to obtain 2D key feature points and their corresponding 3D coordinates?

**Comment by hankyang94** [comment]
The code in https://github.com/NVlabs/ConformalKeypoint/tree/master/keypoint should give you 2D keypoints and 3D keypoints (labelled on the model).

It is a pretrained model from a previous paper, hope it helps.

**Comment by ZHENGXi-git** [comment]
Thank you so much, it's helpful!
